# Generated by Django 4.1.3 on 2022-11-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0002_alter_usuario_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='perfil_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/perfil_img/%Y/%m/%d'),
        ),
    ]
