# Generated by Django 4.1.3 on 2022-11-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0003_usuario_perfil_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil_img',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_img/%Y/%m/%d'),
        ),
    ]
