# Generated by Django 4.1.3 on 2022-11-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField()),
                ('descricao', models.TextField()),
                ('peso', models.FloatField()),
                ('preco', models.FloatField()),
                ('data_fabricacao', models.DateTimeField()),
                ('data_validacao', models.DateTimeField()),
                ('data_entrada', models.DateTimeField()),
            ],
        ),
    ]
