# Generated by Django 4.1.3 on 2022-11-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='protudo_img',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_img/%Y/%m/%d'),
        ),
    ]
