# Generated by Django 4.1.3 on 2022-11-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_carrinho_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='valorTotal',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
