# Generated by Django 4.1.3 on 2022-11-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_produto_protudo_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='protudo_img',
            field=models.ImageField(blank=True, null=True, upload_to='produto_img/%Y/%m/%d'),
        ),
    ]
