# Generated by Django 4.1.3 on 2022-11-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_remove_carrinho_produto_carrinho_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
